### ISSUE TITLE
  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "primary.image.localFile___NODE".

### ISSUE THREAD

**Issue by DaveMitten** [LekoArts/gatsby-starter-prismic#19] opened 2019-01-19 09:50 UTC
Ok, encountered a new error. All I have done since my previous issue was being to edit the homepage (type: homepage) and restart gatsby develop, i tried npm run develop incase there was an issue with the command (trying to cover all bases).

I have no idea why it worked and now it doesn't. Doesn't seem to make sense.

```
success open and validate gatsby-configs — 0.062 s
success load plugins — 0.275 s
success onPreInit — 0.921 s
success delete html and css files from previous builds — 0.015 s
success initialize cache — 0.004 s
success copy gatsby files — 0.086 s
success onPreBootstrap — 0.008 s
⠁ Starting to fetch data from Prismic
⠐ source and transform nodesFetch Prismic data: 891.374ms
success source and transform nodes — 0.945 s
error Encountered an error trying to infer a GraphQL type for: "primary.image.localFile___NODE". There is no corresponding node with the id field matching: "39fba9b7-f9d5-516e-b9db-3f11542c5fc5"


  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "primary.image.localFile___NODE". There is no corresponding node with the id field matching  : "39fba9b7-f9d5-516e-b9db-3f11542c5fc5"
  
  - invariant.js:40 invariant
    [dave-blog-site]/[invariant]/invariant.js:40:15
  
  - infer-graphql-type.js:234 validateLinkedNode
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:234:5
  
  - infer-graphql-type.js:293 inferFromFieldName
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:293:3
  
  - infer-graphql-type.js:359 _.each
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:359:23
  
  - lodash.js:4911 
    [dave-blog-site]/[lodash]/lodash.js:4911:15
  
  - lodash.js:2996 baseForOwn
    [dave-blog-site]/[lodash]/lodash.js:2996:24
  
  - lodash.js:4880 
    [dave-blog-site]/[lodash]/lodash.js:4880:18
  
  - lodash.js:9344 Function.forEach
    [dave-blog-site]/[lodash]/lodash.js:9344:14
  
  - infer-graphql-type.js:338 _inferObjectStructureFromNodes
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:338:5
  
  - infer-graphql-type.js:136 inferGraphQLType
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:136:21
  
  - infer-graphql-type.js:372 _.each
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:372:23
  
  - lodash.js:4911 
    [dave-blog-site]/[lodash]/lodash.js:4911:15
  
  - lodash.js:2996 baseForOwn
    [dave-blog-site]/[lodash]/lodash.js:2996:24
  
  - lodash.js:4880 
    [dave-blog-site]/[lodash]/lodash.js:4880:18
  
  - lodash.js:9344 Function.forEach
    [dave-blog-site]/[lodash]/lodash.js:9344:14
  
  - infer-graphql-type.js:338 _inferObjectStructureFromNodes
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:338:5
  
  - infer-graphql-type.js:136 inferGraphQLType
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:136:21
  
  - infer-graphql-type.js:372 _.each
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:372:23
  
  - lodash.js:4911 
    [dave-blog-site]/[lodash]/lodash.js:4911:15
  
  - lodash.js:2996 baseForOwn
    [dave-blog-site]/[lodash]/lodash.js:2996:24
  
  - lodash.js:4880 
    [dave-blog-site]/[lodash]/lodash.js:4880:18
  
  - lodash.js:9344 Function.forEach
    [dave-blog-site]/[lodash]/lodash.js:9344:14
  

error UNHANDLED REJECTION


  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: "primary.image.localFile___NODE". There is no corresponding node with the id field matching  : "39fba9b7-f9d5-516e-b9db-3f11542c5fc5"
  
  - invariant.js:40 invariant
    [dave-blog-site]/[invariant]/invariant.js:40:15
  
  - infer-graphql-type.js:234 validateLinkedNode
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:234:5
  
  - infer-graphql-type.js:293 inferFromFieldName
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:293:3
  
  - infer-graphql-type.js:359 _.each
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:359:23
  
  - lodash.js:4911 
    [dave-blog-site]/[lodash]/lodash.js:4911:15
  
  - lodash.js:2996 baseForOwn
    [dave-blog-site]/[lodash]/lodash.js:2996:24
  
  - lodash.js:4880 
    [dave-blog-site]/[lodash]/lodash.js:4880:18
  
  - lodash.js:9344 Function.forEach
    [dave-blog-site]/[lodash]/lodash.js:9344:14
  
  - infer-graphql-type.js:338 _inferObjectStructureFromNodes
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:338:5
  
  - infer-graphql-type.js:136 inferGraphQLType
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:136:21
  
  - infer-graphql-type.js:372 _.each
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:372:23
  
  - lodash.js:4911 
    [dave-blog-site]/[lodash]/lodash.js:4911:15
  
  - lodash.js:2996 baseForOwn
    [dave-blog-site]/[lodash]/lodash.js:2996:24
  
  - lodash.js:4880 
    [dave-blog-site]/[lodash]/lodash.js:4880:18
  
  - lodash.js:9344 Function.forEach
    [dave-blog-site]/[lodash]/lodash.js:9344:14
  
  - infer-graphql-type.js:338 _inferObjectStructureFromNodes
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:338:5
  
  - infer-graphql-type.js:136 inferGraphQLType
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:136:21
  
  - infer-graphql-type.js:372 _.each
    [dave-blog-site]/[gatsby]/dist/schema/infer-graphql-type.js:372:23
  
  - lodash.js:4911 
    [dave-blog-site]/[lodash]/lodash.js:4911:15
  
  - lodash.js:2996 baseForOwn
    [dave-blog-site]/[lodash]/lodash.js:2996:24
  
  - lodash.js:4880 
    [dave-blog-site]/[lodash]/lodash.js:4880:18
  
  - lodash.js:9344 Function.forEach
    [dave-blog-site]/[lodash]/lodash.js:9344:14
```

**Comment by DaveMitten** [comment] 2019-01-19 09:54
I tried creating anew post, removing the post that caused issues initially (a post containing an image offered by prismic.io) 

None seems to work and without me having edited any files, I am at a loss.

**Comment by LekoArts** [comment] 2019-01-19 11:50
Try deleting your `.cache` and `public` folder. Then make sure that you don't use any `.gif` for your image slice.

**Comment by ediblecode** [comment] 2019-02-07 20:44
I encountered the same issue and clearing the *.cache* folder worked for me, thanks

**Comment by LekoArts** [comment] 2019-02-07 21:19
Closing this issue then as it's just weird behavior of Gatsby. Happens sometimes 😆

**Closed by LekoArts** 2019-02-07 21:19 UTC
Labels: question

**Comment by halilertekin** [comment] 2019-04-07 03:58
Thank you @LekoArts worked. I try deleting .cache folder.

**Comment by rchrdnsh** [comment] 2019-05-31 23:21
how do I clear the cache?

**Comment by indravb6** [comment] 2019-06-13 21:53
> how do I clear the cache?

@rchrdnsh try "gatsby clean"
https://www.gatsbyjs.org/docs/gatsby-cli/#clean

**Comment by rchrdnsh** [comment] 2019-06-13 21:55
i try that and i get this:

```bash
RN:alma-V13-netlify-test rchrdnsh$ gatsby clean
Usage: gatsby <command> [options]

Commands:
  gatsby develop                   Start development server. Watches files, rebuilds, and hot reloads if something
                                   changes
  gatsby build                     Build a Gatsby project.
  gatsby serve                     Serve previously built Gatsby site.
  gatsby info                      Get environment information for debugging and issue reporting
  gatsby repl                      Get a node repl with context of Gatsby environment, see (add docs link here)
  gatsby new [rootPath] [starter]  Create new Gatsby project.

Options:
  --verbose      Turn on verbose output                                                  [boolean] [default: false]
  --no-color     Turn off the color in output                                            [boolean] [default: false]
  -h, --help     Show help                                                                                [boolean]
  -v, --version  Show version number                                                                      [boolean]

Unknown argument: clean
RN:alma-V13-netlify-test rchrdnsh$ 
```
Seems to be an unknown command for me 🤷‍♂️

**Comment by indravb6** [comment] 2019-06-13 21:58
what's the version?

**Comment by rchrdnsh** [comment] 2019-06-13 21:59
` gatsby: ^2.8.6 => 2.8.6 `

**Comment by indravb6** [comment] 2019-06-13 22:07
i think that's the version of your gatsby in `package.json`, try `gatsby -v`

**Comment by indravb6** [comment] 2019-06-13 22:11
try it, make the following change to package.json:
```
{
  "scripts": {
    "clean": "gatsby clean"
  }
}
```

**Comment by rchrdnsh** [comment] 2019-06-13 22:14
```bash
RN:alma-V13-netlify-test rchrdnsh$ gatsby -v
2.4.3
```

why are these numbers different?

I run `npm update` a bunch, but it doesn't work?

**Comment by x5engine** [comment] 2019-07-11 19:45
confirmed just delete .cache and public folder and you are good to go

**Comment by Prabuela** [comment] 2019-10-16 05:39
No, This was not closed i got same issue it was not yet solved.

**Comment by navdeepsingh** [comment] 2020-04-15 08:55
can use `gatsby clean & gatsby develop` in package.json
